name: Issue
description: Create an issue
title: "Issue: <TITLE>"
labels: ["issue 🪲"]

body:
  - type: textarea
    id: current-behavior
    attributes:
      label: 📝 Current behavior
      description: Provide a clear and concise description of the issue.
      placeholder: The current behavior is...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 📝 Expected behavior
      description: What would be the expected behavior?
      placeholder: The expected behavior would be...
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: ⚙️ Context
      description: Can you provide more information on .NET version, type of project, etc.?
      placeholder: .NET version, NuGet package version...
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: ⚙️ Steps to reproduce
      description: Can you provide steps to reproduce this issue or provide a link to a sample of this problem?
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: 📄 Logs / stack trace
      description: Can you provide a log output or a stack trace?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thank you for submitting this issue! If you're interested in contributing to this project yourself, please read our [Contributing Guidelines](https://github.com/ably-labs/Ably.Healthcheck/blob/main/CONTRIBUTING.md)! 💪
